general {
    lock_cmd = false
    before_sleep_cmd = false
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 999999
    on-timeout = hyprctl keyword monitor eDP-1,disable
    on-resume = hyprctl keyword monitor eDP-1,enable
}

